package net.hawthorn.dndsheets.client.gui;

import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.resources.ResourceLocation;

/**
 * <p>Visual identity shared by the mod's "flat" screens (list panels, short forms, dialogs): a
 * leather-bound tome with brass corner pieces, drawn with the same beveling Minecraft's GUI uses. It's
 * the only place this look lives — changing it here changes it across the forty-plus screens that hang
 * off {@code ListPickerScreen}, {@code SmallFormScreen}, and {@code ModalDialogScreen}.</p>
 *
 * <p><b>Why beveled and not a flat border.</b> Minecraft draws its ENTIRE interface with two bevel
 * lines — light on top and left, dark on bottom and right — over a flat fill. That's what makes a panel
 * "belong" to the game instead of looking like a window pasted on top. The D&amp;D theme comes in
 * through color (dark leather and aged brass) and the corner pieces, not by breaking that grammar.</p>
 *
 * <p>The fill is deliberately near-opaque: the blurred world background still shows through behind it,
 * but without competing with the text. A translucent panel over a snowy biome leaves white text
 * illegible.</p>
 */
public final class GuiStyle {

	//--- Text colors ---
	/** Parchment, not pure white: absolute white over dark leather vibrates and tires the eye.
	 *  Public: also used by the turn HUD (client.TurnHudOverlay), outside this package. */
	public static final int TITLE_COLOR = 0xFFE9D8B4;
	public static final int SUBTITLE_COLOR = 0xFFB9A88C;
	/** Public: the only GuiStyle color consumed by the dungeon toolkit addon (a separate module). */
	public static final int MUTED_COLOR = 0xFF8C8071;
	/** Aged brass, for things that should stand out without shouting (markers, active values). Public, see above. */
	public static final int ACCENT_COLOR = 0xFFC9A227;

	//--- Panel colors ---
	//The fill is a tileable leather texture (generated by tools/make_panel_texture.py, FFT pink noise:
	//seamless by construction, average color = the old FILL_COLOR 0x1A140E) with a translucent depth
	//gradient on top — light falls from above, matching the bevel. The texture gives the pore; the
	//gradient, the volume; text contrast doesn't change from what was already tested, because the
	//midtone is the same.
	private static final ResourceLocation LEATHER = new ResourceLocation("dndsheets", "textures/screens/panel_leather.png");
	private static final int LEATHER_TILE = 64;
	private static final int DEPTH_TOP = 0x2EFFD9A0;    //Warm light on top, translucent.
	private static final int DEPTH_BOTTOM = 0x66000000; //Shadow at the bottom, translucent.
	private static final int BEVEL_LIGHT = 0xFF6B5636;  //Worn brass: light on top and left.
	private static final int BEVEL_DARK = 0xFF0B0906;   //Shadow on bottom and right.
	private static final int EDGE_COLOR = 0xFF2E2418;   //Outer outline, one shade over the fill.
	private static final int STUD_COLOR = 0xFFC9A227;   //Brass corner pieces.

	private static final int STUD_SIZE = 3;

	private GuiStyle() {
	}

	/**
	 * <p>Background panel. The signature is unchanged from the previous version: the forty-plus screens
	 * that call it keep working without being touched. Public: also used by the turn HUD (client.
	 * TurnHudOverlay) so the initiative tracker has the same tome-like look as the rest of the mod
	 * instead of an overlay that belongs to nothing.</p>
	 */
	public static void panel(GuiGraphics guiGraphics, int left, int top, int right, int bottom) {
		//Outer outline first, one pixel outside the bevel: separates the panel from the blurred world
		//behind it without needing a soft shadow, which looks dirty at Minecraft's pixel scale.
		guiGraphics.fill(left - 1, top - 1, right + 1, bottom + 1, EDGE_COLOR);

		//Tiled leather with the same slight transparency the flat fill used to have (0xF2): the world
		//still shows through faintly behind it without competing with the text. setColor affects the
		//next blit and is always restored — leaving it set would tint everything the screen paints
		//afterward. Blending is enabled by hand: blit() draws with whatever state is set (fill() manages
		//it on its own, blit() doesn't), and without blending, setColor's alpha is silently ignored.
		com.mojang.blaze3d.systems.RenderSystem.enableBlend();
		com.mojang.blaze3d.systems.RenderSystem.defaultBlendFunc();
		guiGraphics.setColor(1.0F, 1.0F, 1.0F, 0.95F);
		for (int tileY = top; tileY < bottom; tileY += LEATHER_TILE) {
			for (int tileX = left; tileX < right; tileX += LEATHER_TILE) {
				int tileW = Math.min(LEATHER_TILE, right - tileX);
				int tileH = Math.min(LEATHER_TILE, bottom - tileY);
				guiGraphics.blit(LEATHER, tileX, tileY, 0, 0, tileW, tileH, LEATHER_TILE, LEATHER_TILE);
			}
		}
		guiGraphics.setColor(1.0F, 1.0F, 1.0F, 1.0F);

		guiGraphics.fillGradient(left, top, right, bottom, DEPTH_TOP, DEPTH_BOTTOM);

		//Minecraft-style bevel: light on top/left, dark on bottom/right. Two pixels, not one — at GUI
		//Scale 2 (the normal setting) a one-pixel bevel disappears.
		guiGraphics.fill(left, top, right - 2, top + 2, BEVEL_LIGHT);
		guiGraphics.fill(left, top, left + 2, bottom - 2, BEVEL_LIGHT);
		guiGraphics.fill(left + 2, bottom - 2, right, bottom, BEVEL_DARK);
		guiGraphics.fill(right - 2, top + 2, right, bottom, BEVEL_DARK);

		corners(guiGraphics, left, top, right, bottom);
	}

	//Corner pieces: four brass brackets at the corners, like a bound book's. This is what gives the
	//"tome" impression without drawing a single texture pixel or depending on a PNG.
	private static void corners(GuiGraphics guiGraphics, int left, int top, int right, int bottom) {
		int s = STUD_SIZE;
		int arm = s * 3;

		//Top left.
		guiGraphics.fill(left + 2, top + 2, left + 2 + arm, top + 2 + s, STUD_COLOR);
		guiGraphics.fill(left + 2, top + 2, left + 2 + s, top + 2 + arm, STUD_COLOR);
		//Top right.
		guiGraphics.fill(right - 2 - arm, top + 2, right - 2, top + 2 + s, STUD_COLOR);
		guiGraphics.fill(right - 2 - s, top + 2, right - 2, top + 2 + arm, STUD_COLOR);
		//Bottom left.
		guiGraphics.fill(left + 2, bottom - 2 - s, left + 2 + arm, bottom - 2, STUD_COLOR);
		guiGraphics.fill(left + 2, bottom - 2 - arm, left + 2 + s, bottom - 2, STUD_COLOR);
		//Bottom right.
		guiGraphics.fill(right - 2 - arm, bottom - 2 - s, right - 2, bottom - 2, STUD_COLOR);
		guiGraphics.fill(right - 2 - s, bottom - 2 - arm, right - 2, bottom - 2, STUD_COLOR);
	}

	/**
	 * <p>Horizontal brass rule, to separate a title from its content. Public for screens that want to
	 * mark sections without each one inventing its own line color.</p>
	 */
	public static void rule(GuiGraphics guiGraphics, int left, int right, int y) {
		guiGraphics.fill(left, y, right, y + 1, BEVEL_LIGHT);
	}

	/**
	 * <p>The same rule with a brass diamond in the center — a D&amp;D manual's header ornament, in five
	 * fills. For the rule under a screen's TITLE; internal separators keep using {@link #rule}, because an
	 * ornament repeated per section stops being an ornament.</p>
	 */
	public static void ruleOrnate(GuiGraphics guiGraphics, int left, int right, int y) {
		rule(guiGraphics, left, right, y);
		int cx = (left + right) / 2;
		guiGraphics.fill(cx - 2, y - 1, cx + 3, y + 2, BEVEL_LIGHT);
		guiGraphics.fill(cx - 1, y - 1, cx + 2, y + 2, STUD_COLOR);
		guiGraphics.fill(cx, y - 2, cx + 1, y + 3, STUD_COLOR);
	}
}
