package net.hawthorn.dndsheets.gametest;

import net.hawthorn.dndsheets.Combatant;
import net.hawthorn.dndsheets.Config;
import net.hawthorn.dndsheets.CreatureSize;
import net.hawthorn.dndsheets.CreatureType;
import net.hawthorn.dndsheets.DndsheetsMod;
import net.hawthorn.dndsheets.MonsterRegistry;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.monster.Zombie;
import net.minecraftforge.gametest.GameTestHolder;
import net.minecraftforge.gametest.PrefixGameTestTemplate;

import java.util.List;
import java.util.Map;

/**
 * <p>The other half of invariant 11. {@code JsonContentSelfTest} tests everything that can be tested
 * standing up —the pure rules, the packs, the shape of the network— and by design it can't touch anything that needs
 * a real entity in a real world. That is exactly where the link between the rules and the game lives:
 * the persistent NBT tag by which {@code Combatant.of} recognizes a monster. Until now, the
 * only way to check it was to play.</p>
 *
 * <p>Runs with {@code ./gradlew runGameTestServer}: it starts a server, places {@code dndsheets:arena}
 * (generated by {@code tools/make_gametest_arena.py}), runs each test and exits with the number of failures
 * as the exit code. No client is needed and nobody has to be watching.</p>
 *
 * <p>It tests against the <b>shipped bestiary's goblin</b> and not against a block invented here, for two
 * reasons: that way the test also covers the default pack loading and registering, and because an
 * invented block <em>would not have worked</em> — see {@link #anUnregisteredBlockLeavesTheMobOutside}.</p>
 *
 * <p><b>What does NOT go here.</b> Anything that can be checked without starting the game — a formula, a
 * parser, a conditions table — belongs in the self-test, which takes a second instead of a minute.
 * This is only for what requires a world.</p>
 */
@GameTestHolder(DndsheetsMod.MODID)
@PrefixGameTestTemplate(false) //Without this the template would be looked up as "dndsheets:combatantgametests.arena".
public class CombatantGameTests {

	private static final String GOBLIN = "dndsheets:goblin";

	private static MonsterRegistry.MonsterStatBlock goblin(GameTestHelper helper) {
		MonsterRegistry.MonsterStatBlock block = MonsterRegistry.get(GOBLIN);
		helper.assertTrue(block != null, GOBLIN + " is not in the registry: the default pack did not load");
		return block;
	}

	private static Zombie goblinizedZombie(GameTestHelper helper) {
		Zombie zombie = helper.spawn(EntityType.ZOMBIE, 4, 1, 4);
		MonsterRegistry.applyStatBlock(zombie, goblin(helper));
		return zombie;
	}

	/**
	 * <p>A mob with no stat block has to remain a Minecraft mob. It is invariant 9
	 * checked on a real entity: {@code Combatant.of} returning {@code null} is what makes
	 * the whole 5e engine step aside and let vanilla combat through.</p>
	 */
	@GameTest(template = "arena")
	public static void aMobWithoutABlockStaysOutsideTheRules(GameTestHelper helper) {
		Zombie zombie = helper.spawn(EntityType.ZOMBIE, 4, 1, 4);
		helper.assertTrue(Combatant.of(zombie) == null,
			"a zombie nobody declared anything about has to stay outside the 5e rules");
		helper.succeed();
	}

	/**
	 * <p>The block is applied to an already-living entity —the {@code applyStatBlock} case, which is how a
	 * DM turns something built with another mod into a monster— and {@code Combatant.of} recognizes it with the
	 * right numbers. AC is never scaled; HP is, by difficulty.</p>
	 */
	@GameTest(template = "arena")
	public static void theBlockSurvivesOnTheEntity(GameTestHelper helper) {
		MonsterRegistry.MonsterStatBlock block = goblin(helper);
		Zombie zombie = goblinizedZombie(helper);

		Combatant combatant = Combatant.of(zombie);
		helper.assertTrue(combatant != null, "applyStatBlock did not bring the zombie inside the rules");
		helper.assertTrue(combatant.armorClass() == block.ac(),
			"AC is not scaled by difficulty: expected " + block.ac() + " but got " + combatant.armorClass());

		int expected = Config.scaleMonsterMaxHp(block.maxHp());
		helper.assertTrue(combatant.maxHp() == expected,
			"max HP has to be the block's, already scaled: expected " + expected);
		helper.assertTrue(combatant.currentHp() == expected,
			"a newly declared monster cannot be born wounded");
		helper.assertTrue((int) zombie.getHealth() == expected,
			"vanilla health and 5e HP have drifted apart: the mob's health bar would lie");
		helper.succeed();
	}

	/**
	 * <p>The test that doesn't fit in the self-test. The {@link Combatant} implementations <b>keep no
	 * state of their own</b>: they read and write where the state already lived, which for a monster is its
	 * persistent NBT. Asking for a NEW {@code Combatant} after the hit is what tells "it was written to
	 * the entity" apart from "it stayed in a field of the object" — and the latter would work in any standing-up
	 * test and fail when the chunk reloads.</p>
	 */
	@GameTest(template = "arena")
	public static void damageIsWrittenToTheEntityNotTheObject(GameTestHelper helper) {
		Zombie zombie = goblinizedZombie(helper);

		int before = Combatant.of(zombie).currentHp();
		helper.assertTrue(before > 2, "the goblin has to survive this test's hit");
		Combatant.of(zombie).takeDamage(2);

		int after = Combatant.of(zombie).currentHp(); //New object: if the damage did not persist, it is not here.
		helper.assertTrue(after == before - 2,
			"the damage did not reach the entity's NBT: expected " + (before - 2) + " but it stayed at " + after);
		helper.succeed();
	}

	/**
	 * <p>What the NBT tag carries is the monster's <b>id</b>, not its stats: {@code Combatant.of}
	 * looks them up in the registry every time. So declaring a block that isn't registered leaves the mob
	 * outside the rules, silently and on purpose — it is the same gentle degradation as invariant 9
	 * that protects a game whose DM removed a pack with creatures already summoned in the world: they
	 * become normal mobs instead of blowing up when the chunk loads.</p>
	 *
	 * <p>This test exists because the first attempt at the ones above used a block invented right here
	 * and failed precisely because of this. The behavior is the correct one; what was missing was writing it down.</p>
	 */
	@GameTest(template = "arena")
	public static void anUnregisteredBlockLeavesTheMobOutside(GameTestHelper helper) {
		MonsterRegistry.MonsterStatBlock unregistered = new MonsterRegistry.MonsterStatBlock(
			"test:unregistered", "Unregistered", "minecraft:zombie", 17, 42,
			Map.of("str", 18, "dex", 9, "con", 18, "int", 3, "wis", 11, "cha", 1), 3,
			List.of(), List.of(), Map.of(), Map.of(),
			//null and not Appearance.DEFAULT: that constant is package-private, and widening it to public for a test
			//would be moving the mod's API to accommodate a test. applyLooks treats null and DEFAULT the same.
			CreatureType.CONSTRUCT, 0, 0, 1, CreatureSize.LARGE, null, false, false, false);

		Zombie zombie = helper.spawn(EntityType.ZOMBIE, 4, 1, 4);
		MonsterRegistry.applyStatBlock(zombie, unregistered);

		helper.assertTrue(Combatant.of(zombie) == null,
			"a block that is not in the registry cannot resolve: the tag stores the id, not the stats");
		helper.succeed();
	}
}
