@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.hawthorn.dndsheets;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;
