# Generates the leather texture of the panels (GuiStyle.panel):
#   src/main/resources/assets/dndsheets/textures/screens/panel_leather.png  (64x64, tileable)
#
# It is pink noise generated by inverse FFT: being built in the frequency domain with
# integer frequencies, the tile joins with itself on all four sides WITHOUT seams, which is what
# a normal blur over random noise does not give. Two layers: wide mottling (the "leather") and fine
# grain (the pore). The mean color is GuiStyle's old FILL_COLOR (0x1A140E) so the
# contrast of the text on top does not change from what was already tested.
#
# Fixed seed: regenerating produces EXACTLY the same PNG (same criterion as sync_lang_variants:
# the tool is the source, the binary is derived).
import numpy as np
from PIL import Image
from pathlib import Path

SIZE = 64
BASE = np.array([26.0, 20.0, 14.0])  # 0x1A140E, GuiStyle's leather.
OUT = Path(__file__).resolve().parent.parent / "src/main/resources/assets/dndsheets/textures/screens/panel_leather.png"


def tileable_noise(rng, exponent):
    spectrum = rng.normal(size=(SIZE, SIZE)) + 1j * rng.normal(size=(SIZE, SIZE))
    fx = np.fft.fftfreq(SIZE)[:, None]
    fy = np.fft.fftfreq(SIZE)[None, :]
    freq = np.sqrt(fx ** 2 + fy ** 2)
    freq[0, 0] = 1.0
    spectrum *= freq ** -exponent
    spectrum[0, 0] = 0.0
    noise = np.real(np.fft.ifft2(spectrum))
    return (noise - noise.mean()) / (noise.std() + 1e-9)


def main():
    rng = np.random.default_rng(20260824)
    mottle = tileable_noise(rng, 1.6)   # wide mottling
    grain = tileable_noise(rng, 0.4)    # fine pore
    value = 1.0 + 0.11 * mottle + 0.045 * grain
    # The mottling warms the light areas a little (more red/amber) and cools the dark ones: leather,
    # not gray stone. It is applied as a slight per-channel bias, not as a second noise.
    warm = 1.0 + 0.035 * mottle
    rgb = np.stack([
        BASE[0] * value * warm,
        BASE[1] * value,
        BASE[2] * value / warm,
    ], axis=-1)
    image = Image.fromarray(np.clip(rgb, 0, 255).astype(np.uint8), "RGB")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    image.save(OUT)
    print(f"escrito {OUT} ({SIZE}x{SIZE})")


if __name__ == "__main__":
    main()
