@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.hawthorn.dndsheets.compat;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;
