@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.hawthorn.dndsheets.species;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;
